language: objective-c
osx_image: xcode12.2

cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild -workspace Example/LayoutInspectorExample.xcworkspace -scheme LayoutInspectorExample -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.2,name=iPhone 12" -UseModernBuildSystem=YES test
- pod lib lint
